### PR TITLE
Add operator-sdk boilerplate

### PR DESCRIPTION
**Pull request by russellb**
This commit introduces boilerplate as generated by operator-sdk.  It is
roughly the result of the following commands:

  operator-sdk init --domain=skydive.network --repo=github.com/openshift/skydive-operator
  operator-sdk create api --group config --version v1alpha1 --kind Skydive --resource=true --controller=true

and then I started adding a tiny bit of code in the skydive resource
controller, but it just gets the Skydive resource and does nothing with
it.

The first target is to create a simple working operator to
then iterate on.  The next commits will create a default Skydive
deployment when the Skydive resource exists.

### CODE REVIEW

**Comment by russellb** [comment]
one open question on this is the domain for the API ... I used `skydive.network` since i envisioned this something that could be upstreamed once we have it working well enough.

**Comment by rcarrillocruz** [comment]
I'm fine with the domain, since that's supposed to be upstreamed.
Not sure if it's worth bringing this up on Skydive weekly meeting tho?

**Comment by rcarrillocruz** [comment]
other than that
/lgtm

**Comment by russellb** [comment]
> I'm fine with the domain, since that's supposed to be upstreamed.
> Not sure if it's worth bringing this up on Skydive weekly meeting tho?

or at least on their slack.  I'll note it there.  The weekly meeting isn't compatible with my time zone

**Comment by russellb** [comment]
> > I'm fine with the domain, since that's supposed to be upstreamed.
> > Not sure if it's worth bringing this up on Skydive weekly meeting tho?
> 
> or at least on their slack. I'll note it there. The weekly meeting isn't compatible with my time zone

https://skydive-project.slack.com/archives/C99QJNHNJ/p1603984610059500

**Review by rcarrillocruz — APPROVED** [review]

**Pull request merged**
